'use strict';

const COLORS = {
  accent:    0xF39C12,
  success:   0x10B981,
  danger:    0xEF4444,
  warning:   0xF59E0B,
  info:      0x3B82F6,
  secondary: 0x6366F1,
  dark:      0x0A0A0C,
  surface:   0x1A1A1D,
  muted:     0x6B7280,
};

const EMOJIS = {
  bot:      '🍊',
  on:       '🟢',
  off:      '🔴',
  loading:  '⏳',
  success:  '✓',
  error:    '✗',
  warning:  '⚠',
  info:     'ℹ',
  config:   '⚙️',
  reset:    '🔄',
  back:     '↩️',
  forward:  '➡️',
  save:     '💾',
  delete:   '🗑️',
  edit:     '✏️',
  add:      '➕',
  remove:   '➖',
  channel:  '#',
  role:     '👥',
  user:     '👤',
  text:     '💬',
  voice:    '🔊',
  message:  '📝',
  embed:    '🎨',
  dm:       '✉️',
  clock:    '⏱️',
  join:     '🔔',
  leave:    '👋',
  shield:   '🛡️',
  lock:     '🔒',
  unlock:   '🔓',
  hammer:   '🔨',
  giveaway: '🎁',
  ticket:   '🎫',
  star:     '⭐',
  chart:    '📊',
  trending: '📈',
};

const LABELS = {
  activate:      'Activer',
  deactivate:    'Désactiver',
  configure:     'Configurer',
  reset:         'Réinitialiser',
  back:          'Retour',
  close:         'Fermer',
  save:          'Enregistrer',
  cancel:        'Annuler',
  confirm:       'Confirmer',
  statusOn:      'Activé',
  statusOff:     'Désactivé',
  notConfigured: 'Pas configurée',
  configured:    'Configurée',
  selectChannel: 'Sélectionner un salon',
  selectRole:    'Sélectionner un rôle',
  selectOption:  'Sélectionner une option',
};

module.exports = { COLORS, EMOJIS, LABELS };
